# -*- coding: utf-8 -*- This line is just for your information, the python plugin will not use the first line
insert into about_db values('layer_styles', '*', '', '', '', '','', 'QGIS specific table for storing layer styles in the database','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
CREATE TABLE layer_styles(id INTEGER PRIMARY KEY AUTOINCREMENT,f_table_catalog varchar(256),f_table_schema varchar(256),f_table_name varchar(256),f_geometry_column varchar(256),styleName varchar(30),styleQML text,styleSLD text,useAsDefault boolean,description text,owner varchar(30),ui text,update_time timestamp DEFAULT CURRENT_TIMESTAMP);
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'gvmag','geometry','gvmag','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'gvdel','geometry','gvdel','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'gvflode','geometry','gvflode','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'tillromr','geometry','tillromr','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'strukturlinje','geometry','strukturlinje','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'sprickzon','geometry','sprickzon','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'sarbarhet','geometry','sarbarhet','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
