# -*- coding: utf-8 -*- This line is just for your information, the python plugin will not use the first line
insert into  "zz_gvflode"("typ","beskrivning") values ('huvudmag','i huvudmagasinet');
insert into  "zz_gvflode"("typ","beskrivning") values ('jordlager','i magasin i jordlager (inte huvudmagasinet)');
insert into  "zz_gvflode"("typ","beskrivning") values ('överlagrande magasin','i överlagrande magasin');
insert into  "zz_gvflode"("typ","beskrivning") values ('ytliga jordlager','i ytliga jordlager');
insert into  "zz_gvflode"("typ","beskrivning") values ('berg','i berggrunden');
insert into  "zz_gvflode"("typ","beskrivning") values ('ospec','ospecificierat grundvattenflöde');
insert into  "zz_gvdel"("typ","beskrivning") values ('fast','fast grundvattendelare');
insert into  "zz_gvdel"("typ","beskrivning") values ('rörlig','rörlig grundvattendelare');
insert into  "zz_gvdel"("typ","beskrivning") values ('annan gräns','annan gräns');
insert into  "zz_gvmag"("typ","beskrivning") values ('huvudmag','huvudmagasinet');
insert into  "zz_gvmag"("typ","beskrivning") values ('centralt','central del av huvudmagasinet');
insert into  "zz_gvmag"("typ","beskrivning") values ('jordlager','magasin i jordlager');
insert into  "zz_gvmag"("typ","beskrivning") values ('överlagrande magasin','magasin i jordlager som överlagrar något annat magasin');
insert into  "zz_gvmag"("typ","beskrivning") values ('ytliga jordlager','magasin i ytliga jordlager');
insert into  "zz_gvmag"("typ","beskrivning") values ('berg','magasin i berggrunden');
insert into  "zz_gvmag"("typ","beskrivning") values ('annat','annat magasin, t.ex. ytvatten');
insert into  "zz_gvmag"("typ","beskrivning") values ('ospec','ospecificierat');
insert into  "zz_tillromr"("typ","beskrivning") values ('a','typ a - hela gvbildn infiltrerar direkt till magasinet');
insert into  "zz_tillromr"("typ","beskrivning") values ('b','typ b - hela gvbildn når magasinet via något annat magasin');
insert into  "zz_tillromr"("typ","beskrivning") values ('c','typ c - delar av gvbildn når magasinet');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('spröd','spröd deformationszon');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('plastisk','plastisk deformtionszon');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('strukturell','strukturell formlinje');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('kontakt','litologisk kontakt');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('ospec','ospecificerad strukturlinje');
insert into  "zz_trptid"("typ","beskrivning") values (1,'Extremt kort transporttid');
insert into  "zz_trptid"("typ","beskrivning") values (2,'Kort transporttid');
insert into  "zz_trptid"("typ","beskrivning") values (3,'Genomsnittlig transporttid');
insert into  "zz_trptid"("typ","beskrivning") values (4,'Lång transporttid');
insert into  "zz_trptid"("typ","beskrivning") values (5,'Mycket lång transporttid');
insert into  "zz_omattad_zon"("typ","beskrivning") values (0,'');
insert into  "zz_omattad_zon"("typ","beskrivning") values (1,'Mäktig omättad zon');

